// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwvuex0iWs1fxP7boOfJf4GPgEaish4tI',
    appId: '1:707002192797:web:91032c9ea980c382b29574',
    messagingSenderId: '707002192797',
    projectId: 'closetbuddy27',
    authDomain: 'closetbuddy27.firebaseapp.com',
    storageBucket: 'closetbuddy27.firebasestorage.app',
    measurementId: 'G-DQLNEKX70M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTh8jr6919xTKjNvT9ExTg2-2hZnExi0',
    appId: '1:707002192797:android:3f5210b89d910956b29574',
    messagingSenderId: '707002192797',
    projectId: 'closetbuddy27',
    storageBucket: 'closetbuddy27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCut7pKpIt_iSgAiS06QlDXu5lae-DD4Ys',
    appId: '1:707002192797:ios:ecfd5f5ad595ce02b29574',
    messagingSenderId: '707002192797',
    projectId: 'closetbuddy27',
    storageBucket: 'closetbuddy27.firebasestorage.app',
    iosBundleId: 'com.example.closetBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCut7pKpIt_iSgAiS06QlDXu5lae-DD4Ys',
    appId: '1:707002192797:ios:ecfd5f5ad595ce02b29574',
    messagingSenderId: '707002192797',
    projectId: 'closetbuddy27',
    storageBucket: 'closetbuddy27.firebasestorage.app',
    iosBundleId: 'com.example.closetBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwvuex0iWs1fxP7boOfJf4GPgEaish4tI',
    appId: '1:707002192797:web:7ceb818c9cadeeeeb29574',
    messagingSenderId: '707002192797',
    projectId: 'closetbuddy27',
    authDomain: 'closetbuddy27.firebaseapp.com',
    storageBucket: 'closetbuddy27.firebasestorage.app',
    measurementId: 'G-DM6DEZ25WF',
  );
}
